### ISSUE TITLE
Update limits

### ISSUE THREAD

**Issue by alexellis** [mattevans/ecr-cleanse#1]
> The documented limit to the number of images in an ECR repository is 1000. This is a golang implementation for removing unused images from your ECR repositories.

This is now 10k instead of 1k, I think you should update the README, the tool is still awesome though 👍 

https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecr-now-supports-increased-repository-and-image-limits/

**Comment by mattevans** [comment]
@alexellis Thanks - README updated!
